// Books Database
const booksData = [
    {
        id: 1,
        title: "Dilan 1990",
        author: "Pidi Baiq",
        category: "novel",
        year: 2014,
        price: 85000,
        stock: "ready",
        isRare: false,
        rating: 4.8,
        reviews: 1250,
        image: "foto buku/dilan.jpg",
        condition: "Bekas - Sangat Baik",
        description: "Novel romantis yang menceritakan kisah cinta masa SMA di Bandung tahun 1990. Mengisahkan Dilan, seorang siswa SMA yang jatuh cinta pada Milea dengan cara yang unik dan puitis.",
        synopsis: "Dilan 1990 adalah novel yang mengisahkan pertemuan dan jatuh cintanya Dilan dengan Milea. Dengan setting tahun 1990 di Bandung, novel ini penuh dengan dialog-dialog romantis khas remaja yang membuat pembaca bernostalgia dengan masa SMA.",
        featured: true
    },
    {
        id: 2,
        title: "Twenty Thousand Leagues Under the Sea",
        author: "Jules Verne",
        category: "klasik",
        year: 1870,
        price: 150000,
        stock: "ready",
        isRare: true,
        rating: 4.9,
        reviews: 890,
        image: "foto buku/jules.jpg",
        condition: "Vintage - Edisi Lama",
        description: "Petualangan klasik Jules Verne tentang Kapten Nemo dan kapal selamnya Nautilus. Edisi langka tahun 1950-an dengan ilustrasi asli.",
        synopsis: "Kisah Professor Pierre Aronnax yang terjebak di kapal selam Nautilus milik misterius Kapten Nemo. Mereka menjelajahi kedalaman laut yang belum pernah dijelajahi manusia, menghadapi monster laut, dan menemukan kota Atlantis yang hilang.",
        featured: true
    },
    {
        id: 3,
        title: "Heidi",
        author: "Johanna Spyri",
        category: "klasik",
        year: 1881,
        price: 120000,
        stock: "ready",
        isRare: false,
        rating: 4.7,
        reviews: 456,
        image: "foto buku/heidi.jfif",
        condition: "Bekas - Baik",
        description: "Kisah klasik tentang gadis yatim piatu yang tinggal bersama kakeknya di Pegunungan Alpen Swiss. Cerita hangat tentang keluarga dan persahabatan.",
        synopsis: "Heidi, gadis berusia 5 tahun, dikirim untuk tinggal bersama kakeknya yang penyendiri di pegunungan Alpen. Di sana, ia menemukan kebahagiaan, berteman dengan Peter si penggembala kambing, dan mengubah kehidupan kakeknya dengan keceriaannya.",
        featured: false
    },
    {
        id: 4,
        title: "Etika Nikomakea",
        author: "Aristoteles",
        category: "filsafat",
        year: 350,
        price: 175000,
        stock: "ready",
        isRare: true,
        rating: 4.9,
        reviews: 234,
        image: "foto buku/Etika-Nikomakea.jpg",
        condition: "Vintage - Terjemahan Lama",
        description: "Karya filosofis Aristoteles tentang etika dan kebaikan. Edisi terjemahan Indonesia tahun 1960-an yang sangat langka.",
        synopsis: "Risalah filosofis yang membahas tentang kebahagiaan (eudaimonia) sebagai tujuan tertinggi kehidupan manusia. Aristoteles mengeksplorasi kebajikan moral, kebijaksanaan praktis, dan jalan menuju kehidupan yang baik.",
        featured: true
    },
    {
        id: 5,
        title: "Sapiens: Riwayat Singkat Umat Manusia",
        author: "Yuval Noah Harari",
        category: "sejarah",
        year: 2011,
        price: 145000,
        stock: "ready",
        isRare: false,
        rating: 4.8,
        reviews: 2340,
        image: "foto buku/sapiens.jpg",
        condition: "Baru",
        description: "Sebuah eksplorasi mendalam tentang sejarah umat manusia dari zaman batu hingga era modern. Mengubah cara kita memahami diri sendiri.",
        synopsis: "Harari menelusuri perjalanan Homo sapiens dari spesies tidak penting di Afrika hingga menjadi penguasa planet. Membahas Revolusi Kognitif, Agraris, dan Sains yang membentuk peradaban manusia.",
        featured: true
    },
    {
        id: 6,
        title: "1984",
        author: "George Orwell",
        category: "klasik",
        year: 1949,
        price: 95000,
        stock: "sold-out",
        isRare: false,
        rating: 4.9,
        reviews: 3450,
        image: "foto buku/1948.jpeg",
        condition: "Bekas - Baik",
        description: "Novel dystopian klasik tentang totalitarianisme dan pengawasan massal. Karya yang tetap relevan hingga kini.",
        synopsis: "Di Oceania yang totaliter, Winston Smith bekerja di Kementerian Kebenaran, menulis ulang sejarah. Ia mulai mempertanyakan rezim Big Brother dan jatuh cinta pada Julia, memicu pemberontakan yang berbahaya.",
        featured: false
    },
    {
        id: 7,
        title: "Filosofi Teras",
        author: "Henry Manampiring",
        category: "filsafat",
        year: 2018,
        price: 95000,
        stock: "ready",
        isRare: false,
        rating: 4.7,
        reviews: 1890,
        image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400",
        condition: "Baru",
        description: "Pengantar mudah dipahami tentang filsafat Stoikisme dan aplikasinya dalam kehidupan modern.",
        synopsis: "Buku yang membahas filosofi Stoa (Stoikisme) dari zaman Yunani-Romawi kuno dan bagaimana penerapannya dapat membantu kita menghadapi stres, kecemasan, dan tekanan hidup modern.",
        featured: false
    },
    {
        id: 8,
        title: "Serat Centhini",
        author: "Pakubuwana V",
        category: "sastra",
        year: 1814,
        price: 350000,
        stock: "ready",
        isRare: true,
        rating: 4.8,
        reviews: 123,
        image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400",
        condition: "Vintage - Sangat Langka",
        description: "Karya sastra Jawa klasik yang monumental. Ensiklopedia kehidupan Jawa abad ke-18. Edisi terbatas dengan terjemahan lengkap.",
        synopsis: "Karya sastra Jawa berbentuk tembang yang mengisahkan pengembaraan tiga pemuda mencari ilmu. Mencakup berbagai aspek kehidupan Jawa: adat, filosofi, mistik, seni, dan kehidupan sehari-hari.",
        featured: true
    },
    {
        id: 9,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        category: "klasik",
        year: 1925,
        price: 110000,
        stock: "ready",
        isRare: false,
        rating: 4.6,
        reviews: 2890,
        image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
        condition: "Bekas - Sangat Baik",
        description: "Novel ikonik tentang Jazz Age dan American Dream. Kisah Jay Gatsby dan cinta yang obsesif.",
        synopsis: "Melalui mata Nick Carraway, kita melihat kehidupan misterius Jay Gatsby yang kaya raya di Long Island tahun 1920-an, dan obsesinya untuk mendapatkan kembali cinta lamanya, Daisy Buchanan.",
        featured: false
    },
    {
        id: 10,
        title: "Bumi Manusia",
        author: "Pramoedya Ananta Toer",
        category: "sastra",
        year: 1980,
        price: 125000,
        stock: "ready",
        isRare: true,
        rating: 4.9,
        reviews: 1567,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        condition: "Bekas - Baik",
        description: "Novel pertama dari Tetralogi Buru karya Pram. Kisah Minke di masa kolonial Belanda. Edisi cetak lama.",
        synopsis: "Mengisahkan kehidupan Minke, pemuda Jawa berpendidikan Eropa di awal abad ke-20. Ia jatuh cinta pada Annelies, putri seorang nyai (gundik Belanda). Novel ini mengkritik kolonialisme dan sistem kasta.",
        featured: true
    },
    {
        id: 11,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        category: "klasik",
        year: 1960,
        price: 105000,
        stock: "ready",
        isRare: false,
        rating: 4.8,
        reviews: 4567,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        condition: "Bekas - Baik",
        description: "Novel klasik Amerika tentang rasisme dan kehilangan innocence di Deep South tahun 1930-an.",
        synopsis: "Melalui mata Scout Finch yang berusia 6 tahun, kita menyaksikan ayahnya, pengacara Atticus Finch, membela seorang pria kulit hitam yang dituduh memperkosa wanita kulit putih di Alabama.",
        featured: false
    },
    {
        id: 12,
        title: "Meditations",
        author: "Marcus Aurelius",
        category: "filsafat",
        year: 180,
        price: 195000,
        stock: "ready",
        isRare: true,
        rating: 4.9,
        reviews: 890,
        image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400",
        condition: "Vintage - Terjemahan Langka",
        description: "Refleksi pribadi kaisar Romawi Marcus Aurelius. Teks filosofi Stoik yang paling berpengaruh. Terjemahan Indonesia tahun 1970-an.",
        synopsis: "Catatan pribadi kaisar Romawi tentang filosofi Stoik, cara menghadapi kesulitan hidup, dan mencapai ketenangan batin. Ditulis di medan perang, berisi kebijaksanaan timeless.",
        featured: true
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = booksData;
}
